# Generated by Django 4.2.29 on 2026-03-31 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('type_sauvegarde', models.CharField(choices=[('complete', 'Complète'), ('incrementale', 'Incrémentale')], max_length=20, verbose_name='Type de sauvegarde')),
                ('fichier_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('taille_octets', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reussie', 'Réussie'), ('echec', 'Échec')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('nombre_enregistrements', models.IntegerField(default=0, verbose_name="Nombre d'enregistrements")),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sauvegardes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-date_heure'],
            },
        ),
    ]
