# Generated by Django 4.2.29 on 2026-03-31 05:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('montant_total_du', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total de la consultation/acte', max_digits=10, verbose_name='Montant total dû (€)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('type_paiement', models.CharField(choices=[('consultation', 'Consultation'), ('lunettes', 'Lunettes'), ('traitement', 'Traitement'), ('autre', 'Autre')], default='consultation', max_length=20, verbose_name='Type de paiement')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('reference_externe', models.CharField(blank=True, help_text='N° de chèque, référence virement, etc.', max_length=100, verbose_name='Référence externe')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('valide', models.BooleanField(default=False, help_text="Seul l'admin peut modifier un paiement validé (R12)", verbose_name='Validé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='consultations.consultation', verbose_name='Consultation associée')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date', '-date_creation'],
            },
        ),
    ]
