# Generated by Django 4.2.29 on 2026-03-31 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prescription', models.CharField(choices=[('lunettes', 'Ordonnance lunettes'), ('traitement', 'Traitement médical'), ('examen', 'Examen complémentaire'), ('lentilles', 'Lentilles de contact')], max_length=20, verbose_name='Type de prescription')),
                ('contenu', models.JSONField(default=dict, help_text='Données spécifiques au type de prescription', verbose_name='Contenu de la prescription')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('imprimee', models.BooleanField(default=False, verbose_name='Imprimée')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='consultations.consultation', verbose_name='Consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
