# Generated by Django 4.2.29 on 2026-03-31 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('acuite_od_loin', models.CharField(blank=True, help_text='Exemple: 10/10, 8/10, 3/10', max_length=10, verbose_name='Acuité OD de loin')),
                ('acuite_og_loin', models.CharField(blank=True, max_length=10, verbose_name='Acuité OG de loin')),
                ('acuite_od_pres', models.CharField(blank=True, max_length=10, null=True, verbose_name='Acuité OD de près')),
                ('acuite_og_pres', models.CharField(blank=True, max_length=10, null=True, verbose_name='Acuité OG de près')),
                ('tension_od', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tension OD (mmHg)')),
                ('tension_og', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tension OG (mmHg)')),
                ('diagnostic_principal', models.TextField(verbose_name='Diagnostic principal')),
                ('code_cim10_principal', models.CharField(blank=True, help_text='Ex: H52.1 pour myopie', max_length=20, verbose_name='Code CIM-10 principal')),
                ('diagnostics_associes', models.JSONField(blank=True, default=list, help_text='Liste de diagnostics secondaires avec codes CIM-10', verbose_name='Diagnostics associés')),
                ('actes_realises', models.TextField(blank=True, verbose_name='Actes réalisés')),
                ('observations', models.TextField(blank=True, verbose_name='Observations et notes')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validée'), ('annule', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient', verbose_name='Patient')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='agenda.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_heure'],
            },
        ),
    ]
