# Generated by Django 4.2.29 on 2026-03-31 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
        ('patients', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('cataracte', 'Cataracte'), ('glaucome', 'Glaucome'), ('decollement_retine', 'Décollement de rétine'), ('lasik', 'LASIK / Réfractif'), ('strabisme', 'Strabisme'), ('pterygion', 'Ptérygion'), ('greffe_cornee', 'Greffe de cornée'), ('autre', 'Autre')], max_length=30)),
                ('type_autre', models.CharField(blank=True, max_length=100, verbose_name='Préciser si autre')),
                ('oeil', models.CharField(choices=[('od', 'Œil droit (OD)'), ('og', 'Œil gauche (OG)'), ('les_deux', 'Les deux yeux')], max_length=10)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('pre_op_valide', 'Bilan pré-op validé'), ('realisee', 'Réalisée'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('date_planifiee', models.DateTimeField(verbose_name='Date planifiée')),
                ('anesthesie', models.CharField(blank=True, choices=[('locale', 'Locale'), ('generale', 'Générale'), ('sedation', 'Sédation')], max_length=20, verbose_name="Type d'anesthésie")),
                ('consentement_signe', models.BooleanField(default=False, verbose_name='Consentement signé')),
                ('bilan_pre_op', models.TextField(blank=True, verbose_name='Bilan pré-opératoire')),
                ('date_rdv_pre_op', models.DateField(blank=True, null=True, verbose_name='Date RDV pré-op')),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte-rendu opératoire')),
                ('complications', models.TextField(blank=True, verbose_name='Complications')),
                ('acuite_post_op_od', models.CharField(blank=True, max_length=10, verbose_name='Acuité post-op OD')),
                ('acuite_post_op_og', models.CharField(blank=True, max_length=10, verbose_name='Acuité post-op OG')),
                ('notes_post_op', models.TextField(blank=True, verbose_name='Notes post-opératoires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chirurgien', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.PROTECT, related_name='interventions_chirurgien', to=settings.AUTH_USER_MODEL)),
                ('consultation_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='consultations.consultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_creees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='patients.patient')),
                ('rdv_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention', to='agenda.rendezvous')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='SuiviPostOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_suivi', models.CharField(choices=[('j1', 'J+1'), ('j7', 'J+7'), ('j30', 'J+30'), ('j90', 'J+90'), ('autre', 'Autre')], max_length=10)),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('realise', models.BooleanField(default=False)),
                ('acuite_od', models.CharField(blank=True, max_length=10, verbose_name='Acuité OD')),
                ('acuite_og', models.CharField(blank=True, max_length=10, verbose_name='Acuité OG')),
                ('tension_od', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tension OD')),
                ('tension_og', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tension OG')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='chirurgie.intervention')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rdv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_post_op', to='agenda.rendezvous')),
            ],
            options={
                'verbose_name': 'Suivi post-opératoire',
                'verbose_name_plural': 'Suivis post-opératoires',
                'ordering': ['date_prevue'],
            },
        ),
    ]
