# Generated by Django 4.2.29 on 2026-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('NP', 'Non précisé')], default='NP', max_length=2, verbose_name='Sexe')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('antecedents', models.TextField(blank=True, help_text='Antécédents médicaux personnels et familiaux', verbose_name='Antécédents médicaux')),
                ('allergies', models.TextField(blank=True, help_text='Allergies connues (médicaments, autres)', verbose_name='Allergies')),
                ('traitements_en_cours', models.TextField(blank=True, verbose_name='Traitements en cours')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
