# Generated by Django 4.2.29 on 2026-03-31 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Horodatage (UTC)')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('READ', 'Consultation'), ('LOGIN', 'Connexion'), ('BACKUP', 'Sauvegarde'), ('RESTORE', 'Restauration')], db_index=True, max_length=20, verbose_name='Action')),
                ('entite', models.CharField(db_index=True, max_length=100, verbose_name='Entité concernée')),
                ('entite_id', models.CharField(blank=True, max_length=50, verbose_name="Identifiant de l'entité")),
                ('valeur_avant', models.JSONField(blank=True, null=True, verbose_name='Valeur avant modification')),
                ('valeur_apres', models.JSONField(blank=True, null=True, verbose_name='Valeur après modification')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-horodatage'],
            },
        ),
    ]
