# Generated by Django 4.2.29 on 2026-03-31 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('duree', models.IntegerField(default=20, help_text='Durée du rendez-vous en minutes', verbose_name='Durée (minutes)')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif du rendez-vous')),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('effectue', 'Effectué'), ('annule', 'Annulé'), ('non_presente', 'Non présenté')], default='programme', max_length=20, verbose_name='Statut')),
                ('motif_annulation', models.TextField(blank=True, help_text='Obligatoire si le rendez-vous est annulé', verbose_name="Motif d'annulation")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous_medecin', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_heure'],
            },
        ),
    ]
